services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: myapp/nginx
    container_name: "test-nginx"
    ports:
      - "80:80"
    volumes:
      - ./code:/data/mysite.local
    depends_on:
      - app

  app:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: myapp/php
    container_name: app
    volumes:
      - ./code:/data/mysite.local

  redis:
    image: redis:8.6.4-alpine3.23
    container_name: redis_cache
    restart: always
    volumes:
      - redis_data:/data

  memcached:
    image: memcached:1.6-alpine
    container_name: memcached_cache
    restart: always
    ports:
      - "11211:11211"

  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  redis_data:
  db_data: